-- Execute no banco sqlquerybuilder para experimentar a interface.
CREATE TABLE IF NOT EXISTS clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp with time zone NOT NULL DEFAULT now()
);
